source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"

#use_frameworks!

target 'SmartSleep' do

    pod "AFNetworking"
    pod "SDWebImage"
    pod "SVProgressHUD"
    pod "MJExtension"
    pod "MJRefresh"
    pod "PNChart"

end